### ISSUE TITLE
Worker  vs Consumer

### ISSUE THREAD

**Issue by fntlnz** [stakhanovist/worker#4]
I was having some thoughts about the difference between worker and consumer.

Since we are talking about a message queues messages I think that it's more appropriate to say that a message is "consumed" than that is  "worked" 

This is only a naming question and maybe I'm missing something about this project.

Any thoughts?

**Comment by leogr** [comment]
A worker is a kind of consumer,  that performs jobs.
This package aims to provide a job processing system, not a generic queue message consumer.
Further, the worker allows you to process messages that are not received by the queue, too.
For other purposes that are out of the worker's scope (like a simple inter process comunication), you can use che queue library directly writing your own consumer using the queue client.

**Comment by fntlnz** [comment]
Thank you for the clarification :+1:
